INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/'>
INFO:root:Log response: <HttpResponsePermanentRedirect status_code=301, "text/html; charset=utf-8", url="catalog/">
ERROR:django.request:Internal Server Error: /catalog/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 9, in index
    return JsonResponse("you are at home",s)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/http/response.py", line 724, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <JsonResponse status_code=200, "application/json">
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <JsonResponse status_code=200, "application/json">
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <JsonResponse status_code=200, "application/json">
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <JsonResponse status_code=200, "application/json">
INFO:root:Log request: <WSGIRequest: GET '/favicon.ico'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Log request: <WSGIRequest: GET '/admin/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/admin/catalog/employee/add/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/admin/jsi18n/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/javascript; charset="utf-8"">
INFO:root:Log request: <WSGIRequest: POST '/admin/catalog/employee/add/'>
INFO:root:Log response: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/admin/catalog/employee/">
INFO:root:Log request: <WSGIRequest: GET '/admin/catalog/employee/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/admin/jsi18n/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/javascript; charset="utf-8"">
INFO:root:Log request: <WSGIRequest: GET '/admin/catalog/employee/add/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/admin/jsi18n/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/javascript; charset="utf-8"">
INFO:root:Log request: <WSGIRequest: POST '/admin/catalog/employee/add/'>
INFO:root:Log response: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/admin/catalog/employee/">
INFO:root:Log request: <WSGIRequest: GET '/admin/catalog/employee/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/admin/jsi18n/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/javascript; charset="utf-8"">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
INFO:root:Log request: <WSGIRequest: GET '/catalog/'>
INFO:root:Log response: <JsonResponse status_code=200, "application/json">
INFO:root:Log request: <WSGIRequest: GET '/catalog/api'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /catalog/api
INFO:root:Log request: <WSGIRequest: GET '/catalog/api-auth'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /catalog/api-auth
INFO:root:Log request: <WSGIRequest: GET '/catalog/api-auth/'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /catalog/api-auth/
INFO:root:Log request: <WSGIRequest: GET '/api-auth/'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /api-auth/
INFO:root:Log request: <WSGIRequest: GET '/api-auth/login'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/api-auth/login/'>
INFO:root:Log response: <TemplateResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: POST '/api-auth/login/'>
INFO:root:Log response: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/accounts/profile/">
INFO:root:Log request: <WSGIRequest: GET '/accounts/profile/'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /accounts/profile/
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/urls.py changed, reloading.
INFO:root:Log request: <WSGIRequest: GET '/catalog/rollback/'>
INFO:root:Log response: <HttpResponse status_code=200, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/catalog/api'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
WARNING:django.request:Not Found: /catalog/api
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp'>
INFO:root:Log response: <HttpResponseNotFound status_code=404, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 26, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 26, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
WARNING:django.security.csrf:Forbidden (CSRF cookie not set.): /catalog/emp/
INFO:root:Log request: <WSGIRequest: POST '/catalog/emp/'>
INFO:root:Log response: <HttpResponseForbidden status_code=403, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    emp=Employee.objects.get(emp_name=name)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
catalog.models.Employee.DoesNotExist: Employee matching query does not exist.
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=200, "application/json">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 26, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 13 (char 12)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 30, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    stream=io.BytesIO(json_data)
TypeError: a bytes-like object is required, not 'str'
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/utils/json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 32, in get
    jss=JSONParser().parse(stream)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/rest_framework/parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
ERROR:django.request:Internal Server Error: /catalog/emp/
Traceback (most recent call last):
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/my/django_project/dj/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/my/django_project/locallibrary/catalog/views.py", line 29, in get
    stream=io.BytesIO(json_data)
TypeError: a bytes-like object is required, not 'list'
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=500, "text/html; charset=utf-8">
INFO:django.utils.autoreload:/home/my/django_project/locallibrary/catalog/views.py changed, reloading.
INFO:root:Log request: <WSGIRequest: GET '/catalog/emp/'>
INFO:root:Log response: <HttpResponse status_code=200, "application/json">
